---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-snappcloud-io-v1alpha1-externalservice
  failurePolicy: Fail
  name: vexternalservice.kb.io
  rules:
  - apiGroups:
    - networking.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - externalservices
  sideEffects: None
