# permissions for end users to view externalservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: externalservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lbaas-operator
    app.kubernetes.io/part-of: lbaas-operator
    app.kubernetes.io/managed-by: kustomize
  name: externalservice-viewer-role
rules:
- apiGroups:
  - networking.snappcloud.io
  resources:
  - externalservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.snappcloud.io
  resources:
  - externalservices/status
  verbs:
  - get
